name: fetch_sl_metro_data_quarterly

on:
  #schedule:
    #- cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Create hello world file
        run: |
          echo "Hello world" > data/static/hello_world.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -f data/static/hello_world.txt
          git diff --cached --quiet || git commit -m "Add automated hello world file"
          git push