name: Fetch SL Metro Data Half-Hourly

on:
  schedule:
    - cron: "0,30 6-22 * * *"   # every 30 minutes between 07:00-23:00
  workflow_dispatch:

jobs:
  Quarterly_Pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
        
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          STATIC_API_KEY: ${{ secrets.STATIC_API_KEY }}
          REALTIME_API_KEY: ${{ secrets.REALTIME_API_KEY }}
        run: |
          python -m src.pipeline.1_ingest_and_upload
          ipython src/pipeline/3_inference_pipeline.ipynb

      - name: Store plots
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -f docs/images/
          git diff --cached --quiet || git commit -m "Update forecasts and hindcasts"
          git push
